name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  # schedule:
  #   - cron: '44 4 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

    # lehetővé teszi, hogy "kézzel" elindítsam a folyamatot
    workflow_dispatch:

# env:
  # Use docker.io for Docker Hub if empty
  # REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: generate image tag
        run: |
          echo "IMAGE_TAG=$(date + %s)" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - name: Checkout repository
        run: |
          docker build . --tag ghcr.io/kecske5000/test-ci-cd:$IMAGE_TAG
          docker login ghcr.io -u kecske5000 -p ${{ secrets.GHCR_TOKEN }}
          docker push ghcr.io/kecske5000/test-ci-cd:$IMAGE_TAG